### ISSUE TITLE
Wasm service worker and htmx  idea

### ISSUE THREAD

**Issue by gedw99** [mikestefanello/pagoda#16]
There is a rust example here: https://www.reddit.com/r/htmx/comments/y64ian/wasmservice_proof_of_concept_for_htmx_webassembly/

The concept I like is to render off the server to ensure fast initial load and then boot strap the Service worker. 

The Service worker is just a version of the golang backend that acts as a proxy.

Use cases ?

Quasi db and template rendering . In the same way that the cache uses tags and they are invalidated by the DAL , we could invalidate data and hence rendered templates in the service worker.

Materialised views are its data. The Bsckend DB produces data , and we cache it in Redis. We could extend it to the Service worker .

both the above examples require the Server to fire events to the Service worker to tell it that data is invalidate. 

Posts from the Browser DOM to the Service Worker could do validation , and if passed get fed further to the backend where further validation is sometimes required. 

Building a service worker just requires the service.js and the wasm ( originally golang ) will load.

The htmx Ajax would route through to the Service Worker. Just like it does now to the backend.

**Comment by mikestefanello** [comment]
I don't understand what benefit this provides, though I probably don't even fully understand what the proposal is.

> The concept I like is to render off the server

Go (server) is already doing the HTML rendering. That is what is sent to HTMX. And the cache is available to either cache data, HTML, or whatever you prefer.

Can you elaborate more on what this provides and what the benefits are?

**Comment by gedw99** [comment]
Ok let me just try to explain it this way. 

Htmx is all about sending html to the client to replace parts of the page.

With “wasm htmx” you send wasm. The wasm has logic and html templstes.

Now you have the same wasm running on the server for the need fast “ time to interaction “, but you progressively move that same wasm to the client .

The client wasm can cache data , and so do things itself.

the client wasm can hold a per user store , and that per user store is of course able to render things. But the big thing is that with modern CDC / materialised views patterns , the user store can be sent data updates ( crud events to changes its materialised view ).

Hope this makes more sense and you see the benefits.

**Comment by mikestefanello** [comment]
Thanks for the explanation. I haven't worked with wasm before, so I'm not immediately seeing the benefit, especially as it relates to this project. My intention with this project is to provide out-of-the-box functionality for what almost all webapps will require. Since I don't think any will _require_ this necessarily, I don't think it's something that I would opt to include, especially because it introduces complexity and the overall learning curve of the project. Thank you for sharing this and suggesting it though.

**Comment by gedw99** [comment]
agree - . web apps don't need this.
