### ISSUE TITLE
Alias "docker compose" in makefile so it works on macs also

### ISSUE THREAD

**Issue by gedw99** [mikestefanello/pagoda#17]
On a mac its "docker-compose", not "docker compose".

I changed the makefile like this:

``` 
# mac name
DCO_BIN_NAME=docker-compose
# linux name
#DCO_BIN_NAME=docker compose

....

# Start the Docker containers
.PHONY: up
up:
	$(DCO_BIN_NAME) up -d
	sleep 3

```

**Comment by mikestefanello** [comment]
Are you using the latest version of Docker?

**Comment by mikestefanello** [comment]
There's probably an easy way to include something in the makefile that will assign the name of executable based on if docker-compose is installed or not. I wasn't able to quickly figure it out in a way that will work cross-platform.

**Comment by gedw99** [comment]
will send a PR if i get it working.

i use colima, so that i don't need docker desktop..

**Comment by mikestefanello** [comment]
This should do it: https://github.com/mikestefanello/pagoda/commit/26e4d4d16a614910a88de6235e7ad5d81a9fbf5a

Please let me know and re-open this issue if it doesn't work for you.

I also hard-coded the container names so the db and cache make targets work as well.
