### ISSUE TITLE
kataras/blocks instead of bespoke template solution?

### ISSUE THREAD

**Issue by endigma** [mikestefanello/pagoda#18]
https://github.com/kataras/blocks is a fully working competent wrapper for `html/template`, it would likely be an upgrade to use it's API instead of the current one due to blocks' full support of multi-layout multi-page and partials with an easy to use interface. It also supports markdown content ootb using blackfriday.

**Comment by mikestefanello** [comment]
Thanks for the suggestion. That looks like an interesting project. However, I do prefer what is currently included for several reasons. It avoids another dependency. The code (which isn't much at all) lives within this project so like everything else, it's available for the dev to directly manipulate for their own needs. It covers all of the required use-cases pretty well (in my opinion). And it's very simple to use. And like all things, it could easily be dropped in favor of _blocks_ if the dev prefers that. If I didn't already write what I did, I would definitely be more open to it.
