### ISSUE TITLE
This template is really awesome, thanks!

### ISSUE THREAD

**Issue by joshlemer** [mikestefanello/pagoda#19]
Sorry for the unnecessary issue, but I had to say this starter project is really really cool. I love the decisions you guys have made on it, the initial project functionality is a really great demo/example, really nice touches with the docker-compose, hooking up the redis cache, and make scripts and everything. The documentation on the README is great too. Very well done thanks everyone!

**Comment by mikestefanello** [comment]
Absolutely no apology needed. I welcome, encourage, and look forward to feedback of all kind; especially if it's very positive like yours. I'm very happy to hear that you like this project and are finding it useful. It was a lot of fun to make and I hope to find some time to continue working on it in the near future. If you have any other feedback, ideas, suggestions, improvements, questions, etc, please don't hesitate to reach out.

Thanks!
