### ISSUE TITLE
Gorilla no longer maintained

### ISSUE THREAD

**Issue by mips171** [mikestefanello/pagoda#23]
Unfortunately, Gorilla seems like it will no longer be maintained
https://github.com/gorilla/

**Comment by mikestefanello** [comment]
Thanks for letting me know. The only package being used is [sessions](https://github.com/gorilla/sessions, which is what [Echo](https://echo.labstack.com/middleware/session/) supports. Do you know if they are planning to move to something else?

**Comment by mips171** [comment]
I don't know, but I did a quick check and[ Echo seems to be aware, and are not in a hurry](https://github.com/labstack/echo/discussions/2361) to migrate unless there are problems.

**Comment by mikestefanello** [comment]
We'll address this when needed.
