### ISSUE TITLE
Rebuilding after file edits

### ISSUE THREAD

**Issue by Jimmy99** [mikestefanello/pagoda#27]
Thanks for this great project! I issue ctrl-C and make run every time I edit a file to rebuild and restart the server. Is this the correct approach or is there a filesystem watcher that I am not using properly?

**Comment by mikestefanello** [comment]
You're very welcome!

Locally, this app will only hot-reload changes made to the HTML template files. It will not work with `.go` files and you will have to do what you're doing.

There is a project called [air](https://github.com/cosmtrek/air) that achieves what you're describing with `.go` files. I suggest giving that a try.
