### ISSUE TITLE
hthx example

### ISSUE THREAD

**Issue by gedw99** [mikestefanello/pagoda#3]
I am a golang dev. thanks for making this nice and clean golang base.

htmx really looks like an answer to so many gui issues.

would be great if you added a htmx example, so i can see how to join up the front and back.

**Comment by mikestefanello** [comment]
You're welcome and thank you. I'm glad to hear that you like it.

There are many HTMX examples included. First, please make sure you've read the [HTMX section](https://github.com/mikestefanello/pagoda#htmx-support) of the README.

The current HTMX examples provided are:
- All sidebar navigation links use hx-boost to fetch and replace the body
- Click the search bar. A modal will appear which is done with Alpinejs. Type a few characters. hx-get is used to fetch mock search results from the server and render them on the screen.
- All forms (contact, login, register, forgot password, etc) either use hx-boost or hx-post.
- On the dashboard/homepage, you can page through the mock "posts" using hx-get.
- The contact form, when submitted successfully, will fetch markup from the server to replace the form using hx-post.

The HTMX package to handle the request and response headers can be found [here](https://github.com/mikestefanello/pagoda/blob/main/htmx/htmx.go). As the README explains, it should be used via the [Page](https://github.com/mikestefanello/pagoda/blob/main/controller/page.go)

I believe that is it for now. If you have a suggestion for other examples to include or have any questions, please let me know.
