### ISSUE TITLE
Cannot connect to database on non standard port

### ISSUE THREAD

**Issue by AntmanLFEz** [mikestefanello/pagoda#4]
The database port from the configuration is ignored when creating the postgres connect string. This defaults to the standard port `5432` which in my case is not where the postgres server is.

I updated in `container.go` to the following to be able to spin this up.

```go
	getAddr := func(dbName string) string {
		return fmt.Sprintf("postgresql://%s:%s@%s:%s/%s",
			c.Config.Database.User,
			c.Config.Database.Password,
			c.Config.Database.Hostname,
			strconv.Itoa(int(c.Config.Database.Port)),
			dbName,
		)
	}
```

**Comment by mikestefanello** [comment]
Thanks for reporting that. I pushed a fix: https://github.com/mikestefanello/pagoda/commit/c6a50b3bbf9ec6a5d05fd6d429b0f24118d2680b
