### ISSUE TITLE
Flash messages when using HTMX

### ISSUE THREAD

**Issue by barthr** [mikestefanello/pagoda#40]
When using HTMX the full template is not rendered on the backend (which means that flash messages are not processed). How should we use flash messages when using htmx powered forms ?

It is possible to include the "messages" but I was wondering if these are in the base template and you would like to show flash messages not in the form but in the base template. I'm not sure if this can even work, given the semantics of what is actually rendered (just the html which should be changed and not the whole template)

So any tips on patterns would be greatly appreciated!

**Comment by mikestefanello** [comment]
Did you figure it out?

**Comment by barthr** [comment]
Yes! I could just include the message template in the htmx template and voila!
