### ISSUE TITLE
htmx problem

### ISSUE THREAD

**Issue by Jimmy99** [mikestefanello/pagoda#47]
I am trying to implement the functionality to bulk update as set out in https://htmx.org/examples/bulk-update/
It seems that the swap of the tbody element isn't being done properly since the checkboxes are not visible but they do appear in the html, and the button elements are repeated. (which seems to indicate that it is not just the tbody which is being swapped but other elements on the page (or maybe the whole page) 
In your experience with htmx, do you have any tips about where to start troubleshooting this?

**Comment by mikestefanello** [comment]
I'm not sure what the problem would be. I haven't tried out that functionality yet and I would need to see the complete code that you're working with. If you post it, I can take a look (feel free to reopen this ticket with that). I would recommend opening a ticket with the htmx project or checking out their Discord. Last I checked, it's very active, and they even have a channel just for Go discussion.
