### ISSUE TITLE
Getting started improvements for newbies

### ISSUE THREAD

**Issue by hubyhuby** [mikestefanello/pagoda#5]
It would nice to have an explaination on the command line to get the project to work quickely.

1)  go get didn t work on my Ubuntu 20.04 I was asked to use go isntall
"
go: downloading github.com/google/go-cmp v0.5.6
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
"
2) A little explaination on how to install docker. 
In the readme it is assumed that we know docker... Some persons like me don t.
On ubuntu do : 
snap install docker
cd ~/go/pkg/mod/github.com/mikestefanello/pagoda@v0.4.0
$ make up
"
Status: Downloaded newer image for postgres:alpine
Creating pagodav040_cache_1 ... 
Creating pagodav040_db_1    ... 
Creating pagodav040_db_1    ... error

Creating pagodav040_cache_1 ... done
5e2b0267327e1f48384ad): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint pagodav040_db_1 (b1f6e840f3529cf0eb014fb1428118e3b55481e8f5d5e2b0267327e1f48384ad): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:39 : up] Erreur 1

"

**Comment by mikestefanello** [comment]
The challenge with providing instructions for setting up things like Docker is that it will differ based on your operating system, and even within a given OS, there are several options. Also, Docker isn't required. You can manually install both Postgres and Redis, if you prefer to do so. And last, if those instructions are provided in this repo, they run the risk of becoming outdated as opposed to getting instructions and documentation directly from those projects.

I'm not sure what you're using `go get` for while setting up this project. I'd recommend just checking out the repo, then running `make up` and `make run` within the root of it:

```
git clone git@github.com:mikestefanello/pagoda.git
cd pagoda
make up
make run
```

As for the _bind_ error you received, it looks like the port `5432` is already in use. Do you have a local installation of Postgres already running on your computer? If so, it will conflict with the instance running in Docker. You can either stop your local version, use a different port for your local version, use a different port for the Docker version, or just use your local version rather than Docker's for this application.

**Comment by matrixik** [comment]
I think it would be good to add these steps to readme and point out that `go get` will not work because it's a code template, not a library.

**Comment by mikestefanello** [comment]
> I think it would be good to add these steps to readme and point out that `go get` will not work because it's a code template, not a library.

Agreed - that's a good idea. I will add that in.

**Comment by mikestefanello** [comment]
I added some extra information to the README. The [Getting started](https://github.com/mikestefanello/pagoda#getting-started) section did mention checking out the repo, but I added the commands and a message explaining not to use `go get`.

https://github.com/mikestefanello/pagoda/commit/089c4d7ee1fc5a42a58952b5051051d2ba7f0faf

**Comment by mips171** [comment]
I'm using the docker-in-docker VS Code devcontainer, just need to install Go. Here's my dockerfile and a couple of post start scripts

post_create.sh

```
#!/bin/bash

# This command is the last of three that finalizes container setup when a dev container is created.
# Runs after updateContentCommand and after the dev container has been assigned to a user for the first time.
# You can use this to install software specific to the container user.

# Read more https://containers.dev/implementors/json_reference/#lifecycle-scripts
echo "Running post-create shell script"

# Set your go version here
GO_VERSION=1.19.4

GIT_EMAIL="your_email"
GIT_USERNAME="your_name"

# Setup git
git config --global user.email "$GIT_EMAIL"
git config --global user.name "$GIT_USERNAME"
git config --global init.defaultBranch main

curl -L https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz -O -J \
&& tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz  \
&& export PATH=$PATH:/usr/local/go/bin \
&& sudo apt update \
&& sudo apt install gopls delve
```

post_start.sh

```
#!/bin/bash

systemctl start docker

cd /workspace/pagoda \
&& make ent-install \
&& make ent-gen \
&& make up \
&& make run
```

devcontainer.json

```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/docker-in-docker
{
	"name": "Docker in Docker",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
			"version": "latest",
			"enableNonRootDocker": "true",
			"moby": "true"
		},
		"ghcr.io/devcontainers/features/go:1": {},
		"ghcr.io/guiyomh/features/golangci-lint:0": {},
		"ghcr.io/guiyomh/features/gotestsum:0": {}
	},
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Set *default* container specific settings.json values on container create.
			"settings": {
				"go.toolsManagement.checkForUpdates": "local",
				"go.useLanguageServer": true,
				"go.gopath": "/go",
				"gopls": {
					"ui.semanticTokens": true
				}
			},
			"extensions": [
				"golang.go",
				"jinliming2.vscode-go-template",
				"aaron-bond.better-comments",
				"streetsidesoftware.code-spell-checker",
				"fabiospampinato.vscode-diff",
				"usernamehw.errorlens"
			]
		}
	},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Use 'postCreateCommand' to run commands after the container is created.
	"postCreateCommand": "/workspace/.devcontainer/post_create.sh",
	"postStartCommand": "/workspace/.devcontainer/post_start.sh",
	// Configure tool-specific properties.
	// "customizations": {},
	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
	//
	// Remove the `,Z` on the next line if you are using Docker instead of Podman
	"workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,Z",
	"workspaceFolder": "/workspace",
	"runArgs": [
		"--userns=keep-id"
	],
	"containerUser": "vscode"
}
```
