### ISSUE TITLE
Create a space for discussions, support and future roadmap planning

### ISSUE THREAD

**Issue by jbowa** [mikestefanello/pagoda#56]
Hi Mike, I find this project extremely helpful and with the trend that HTMX is going through right now I can only assume that a modern stack like this would serve a lot of community members. Was wondering whether it was worthwhile creating a Slack/Discord for like minded people working on this project to share their experience, help with any issues, recommendations and future roadmap. Happy to setup something and create a PR for the readme if that helps.

**Comment by mikestefanello** [comment]
Hey. Always glad to hear that this project has been helpful. HTMX has a Discord that's very active and they have a separate channel specifically for Go. That may be a good place to start and it will have a wider audience than just people who use this project. Have you checked that out yet?

**Comment by jbowa** [comment]
Agree. Thank you.
