### ISSUE TITLE
url should change after successful login 

### ISSUE THREAD

**Issue by msonawane** [mikestefanello/pagoda#6]
after successful post URL stays /user/login even if we are on home page.

there are two ways to fix this 
in handler add HX-Push header [https://htmx.org/docs/#response-headers](url)
`ctx.Response().Header().Set("HX-Push", url) `

OR
 dont do a 302 redirect and send html content back from handler ( in case of login 302 is better)

any other better  way to fix this ?

**Comment by mikestefanello** [comment]
Thanks for reporting this. I can confirm the issue exists with both the login and register form. I'll work on a fix.

**Comment by mikestefanello** [comment]
Sorry for the delay. I spent some time researching this but didn't have time to work on the fix.

This was surprisingly tricky to resolve. HTMX recommends avoiding the post/redirect/get pattern for forms and just having the post handler return the content for the next page. That's fine unless you want to support users without JS enabled. If that was the case, they would remain stuck on the original URL.

I think I have a decent workaround. In the `controller` package we have a helper to handle redirects:

```go
// Redirect redirects to a given route name with optional route parameters
func (c *Controller) Redirect(ctx echo.Context, route string, routeParams ...interface{}) error {
	url := ctx.Echo().Reverse(route, routeParams)
	return ctx.Redirect(http.StatusFound, url)
}
```

I made an adjustment to check if the current request is an HTMX booster request, and if so, only return an HTMX redirect to instruct it to handle the redirect on the client side:

```go
// Redirect redirects to a given route name with optional route parameters
func (c *Controller) Redirect(ctx echo.Context, route string, routeParams ...interface{}) error {
	url := ctx.Echo().Reverse(route, routeParams)

	if htmx.GetRequest(ctx).Boosted {
		htmx.Response{
			Redirect: url,
		}.Apply(ctx)

		return nil
	} else {
		return ctx.Redirect(303, url)
	}
}

```

It does cause a complete refresh, but if you were redirecting, it's expected. The only other option, I think, is to somehow adjust this to fetch the content of the redirect destination and just return that.

Let me know what you think.
