### ISSUE TITLE
what is the correct use of page.Form

### ISSUE THREAD

**Issue by Jimmy99** [mikestefanello/pagoda#62]
I understand how regular input fields are used in page.Form, but what is the correct approach for say select elements where there are options to select and the selected option too?

**Comment by mikestefanello** [comment]
Great question. Rather than answer, I thought it made sense to just include an example so others can see how to do it. It's very easy. Let me know if you still have any questions: https://github.com/mikestefanello/pagoda/commit/30389de16f40b2ef1a6dce1e961a9fb65da7225e
