### ISSUE TITLE
Livewire/Liveview like component

### ISSUE THREAD

**Issue by alaibe** [mikestefanello/pagoda#74]
First of all awesome job!

Would you think it would be possible to create an abstraction to htmx that makes it more like writing component in the same way it is being done in livewire /liveview?

**Comment by mikestefanello** [comment]
Thank you!

I have not used livewire/liveview. Can you provide some explanation as to how it works or what sort of functionality/ux you're interested in? Or perhaps a link to some examples and/or documentation? I'm definitely interested in making the frontend as easy to write and manage as possible.

**Comment by alaibe** [comment]
Here are the docs I am referring to:
https://livewire.laravel.com/docs/quickstart
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html

As you can see in both cases, it allows to make components like.
HTMX is clearly similar and allows to build in such a way but is way less opinionated.

**Comment by mikestefanello** [comment]
Thanks for sharing that. I will take a good look at it soon. There's another open discussion (https://github.com/mikestefanello/pagoda/issues/75) to adopt [templ](https://github.com/a-h/templ) in to this project. I haven't yet fully explored it, but I believe using that would make building _components_ like that much easier. Have you worked with templ at all?

**Comment by mikestefanello** [comment]
I'm going to close this in favor of https://github.com/mikestefanello/pagoda/issues/75 - let's keep move the discussion there since I think if templ is adopted, that will satisfy what you're looking for.
