### ISSUE TITLE
Pager.isBeginning() returns false for "empty" pager

### ISSUE THREAD

**Issue by humpalum** [mikestefanello/pagoda#77]
Hey, 

It seems like the Pager returns false when items is 0. 
This is because the page is set to 0 when  items are 0

```
func (p *Pager) SetItems(items int) {
	p.Items = items
	p.Pages = int(math.Ceil(float64(items) / float64(p.ItemsPerPage)))

	if p.Page > p.Pages {
		p.Page = p.Pages
	}
}
```

For me this is an edge case and im not sure if you would like to fix it in the SetItems or in the isBeginning.

Would you say you are on page 1 when there are no items or do you want to define page 0 to also mean "no Items"?

So i would propose one of these 2 fixes:

```
func (p *Pager) SetItems(items int) {
	p.Items = items
	p.Pages = int(math.Ceil(float64(items) / float64(p.ItemsPerPage)))
	if items == 0 {
		return 1
	}
	if p.Page > p.Pages {
		p.Page = p.Pages
	}
}
```

or 

```
func (p Pager) IsBeginning() bool {
	return p.Page == 1 || p.Page == 0
}

```

**Comment by mikestefanello** [comment]
Nice catch - thanks for reporting. I think the page should always be 1. I'll fix this and report back once it's committed.

**Comment by mikestefanello** [comment]
https://github.com/mikestefanello/pagoda/commit/a9319559e15ca9f38851962d751c4bdf536dea1b
