### ISSUE TITLE
How to Query data by ORM with condition(ORDER BY, LIMIT, ..)

### ISSUE THREAD

**Issue by akiranguyenvni** [mikestefanello/pagoda#9]
Hi Mikestefanello,
In routes, I attempts to Query n latest data that saved in db before.
Assume, I want to Query 14 newest posts(latest created_at).
I coded this code:
```go
// ./routes/posts.go
...
	smt, err := c.Container.ORM.Posts.
		Query().
		Order(ent.Desc("created_at")).
		Limit(14).
		Only(ctx.Request().Context())
...
```
but it returned error:
```
ent: posts not singular
```
Could you tell me what is correct way to use `.Order()`?

Thanks

**Comment by mikestefanello** [comment]
Did you go through Ent's [documentation](https://entgo.io/docs/getting-started)? It's extremely well-written and comprehensive. What stands out to me is you're using `Only()` which is used when you are expected 1 an only 1 result. For a limit query like this, I believe `All()` is what you want.

**Comment by akiranguyenvni** [comment]
Thank Mikestefanello. That's correct. After replacing `Only` with `All`, It's all Okay.
